export const CONSTANTS = {

	CHOICE_MADE: 'CHOICE_MADE',
	CHOICE_UPDATE: 'CHOICE_UPDATE',
	REMAINING_DECREMENT: 'REMAINING_DECREMENT',
	MENU_UPDATE: 'MENU_UPDATE',
	MAP_UPDATE: 'MAP_UPDATE',
	SCORE_UPDATE: 'SCORE_UPDATE',
	MAYOR_TALKS: 'MAYOR_TALKS',
	HOTPOINT_UPDATE: 'HOTPOINT_UPDATE'

}
